[project]
name = "openbachelorc"
version = "0.1.0"
description = ""
authors = [{ name = "Your Name", email = "you@example.com" }]
readme = "README.md"
requires-python = ">=3.12,<3.15"

dependencies = [
    "frida (==17.9.1)",
    "prompt-toolkit (>=3.0.53,<4.0.0)",
    "requests (>=2.34.2,<3.0.0)",
    "lief (>=1.0.0,<2.0.0)",
]

[tool.poetry]
packages = [{ include = "openbachelorc", from = "src/launcher" }]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.16.10"
pytest = "^9.1.1"
poethepoet = "^0.48.0"
pyinstaller = "^6.22.3"
pycryptodome = "^3.24.0"

[tool.poetry.scripts]
main = "openbachelorc.main:main"

[tool.poe.tasks]
locker = { script = "locker:main" }
